---
config:
  theme: forest
---
stateDiagram-v2
    direction LR
    [*] --> Accueil
    Accueil --> ChoixUtilisateur: Sélection du type d'utilisateur
    ChoixUtilisateur --> AuthentificationAdmin: Choix Administrateur
    AuthentificationAdmin --> EchecAuthentification: Échec
    EchecAuthentification --> AuthentificationAdmin: Réessayer
    AuthentificationAdmin --> VerificationGrade: Succès
    VerificationGrade --> VueAdmin: Grade Admin
    VerificationGrade --> VueSuperAdmin: Grade SuperAdmin
    VueAdmin --> GestionRuches: Afficher liste
    VueAdmin --> ParametrageAlertes: Gérer alertes
    VueAdmin --> AjouterRuche: Ajouter ruche
    VueAdmin --> SupprimerRuche: Supprimer ruche
    VueSuperAdmin --> GestionRuches: Afficher liste
    VueSuperAdmin --> GestionUtilisateurs: Gérer utilisateurs
    VueSuperAdmin --> ParametrageAlertes: Gérer alertes
    GestionUtilisateurs --> CreerUtilisateur
    GestionUtilisateurs --> SupprimerUtilisateur
    GestionUtilisateurs --> ModifierMotDePasse
    GestionUtilisateurs --> ModifierGrade
    ChoixUtilisateur --> VueUtilisateur: Choix Utilisateur
    VueUtilisateur --> ConsultationRuches: Consulter ruches
    GestionRuches --> ConsultationDonnees: Sélectionner ruche
    ConsultationRuches --> ConsultationDonnees: Sélectionner ruche
    ConsultationDonnees --> AffichageCapteurs: Voir capteurs
    ConsultationDonnees --> AffichageGraphiques: Voir graphiques
    ConsultationDonnees --> AffichageTableauDonnees: Voir tableau
    ConsultationDonnees --> GestionImages: Gérer images
    AffichageCapteurs --> VerificationAlertes
    VerificationAlertes --> NotificationAlerte: Si seuil dépassé
    AffichageGraphiques --> SelectionCapteur
    SelectionCapteur --> AffichageGraphiques: Mise à jour
    AffichageTableauDonnees --> FiltrerDonnees
    FiltrerDonnees --> AffichageTableauDonnees: Actualiser
    GestionImages --> ImporterImage
    GestionImages --> SupprimerImage: Si admin
    ParametrageAlertes --> AfficherAlertes
    AfficherAlertes --> AjouterAlerte
    AfficherAlertes --> SupprimerAlerte
    AfficherAlertes --> ModifierAlerte
